# For creating plots from data generated by MoodMeasure
# Install ggplot2, if not already installed
if (!require(ggplot2)){install.packages('ggplot2')}; library(ggplot2)

WINDOW_SIZE = 700  # Size of MoodMeasure window, in pixels

data_file <- read.csv(file.choose())  # dialog box for user to select file
p_to_use <- 'test participant'  # enter name of participant to use here

# Filter data by participant, and scale as desired (default = 100)
# NOTE: scaling factor 100 means data will range from -100 to 100, for arousaland valence
filter_data <- function(p_to_use, data_scaling_factor = 100){
    p_data <- data_file[data_file$P_ID == p_to_use, ]
    p_data$Arousal <- p_data$Arousal / ((WINDOW_SIZE / 2) / data_scaling_factor)
    p_data$Valence <- p_data$Valence / ((WINDOW_SIZE / 2) / data_scaling_factor)
    p_data
}

filtered_data <- filter_data(p_to_use)

# Make the plots of arousal and valence ratings over time
arousal_plot <- ggplot(filtered_data, aes(x=Song_time, y=Arousal)) + geom_line(size=2) +
    theme(axis.title.x=element_blank()) +
    ggtitle('Arousal and valence ratings') +
    theme(axis.title=element_text(face='bold', size=14), axis.text=element_text(size=12),
          plot.title=element_text(face='bold', size=16, hjust = 0.5))

valence_plot <- ggplot(filtered_data, aes(x=Song_time, y=Valence)) + geom_line(size=2) +
    xlab('Position in music (secs)') +
    theme(axis.title=element_text(face='bold', size=14), axis.text=element_text(size=12))

# Arrange plots in two-panel view
grid.arrange(arousal_plot, valence_plot, ncol=1)
